### PR TITLE
Edit streamlit layout

### PR DESCRIPTION
**Pull request by ICWallis**
Hey guys. We used the app for a project about a week ago and I got some good feedback from others on what would be useful. 

Changes include: 

- Dealing with the figure that was not showing (removed it and replaced it with a link to the paper)
- Simplified some of the text and the overall layout 
- Split the temp inputs to go with the power density discussion and to make it clearer that these are not used in the power capacity calculation
- Added a results summary between in input and the plot (we were just taking a screen shot of each scenario, so it was nice to have everything in one view)
- Added an option where the user could set the x-axis of the plot (we were working on a smallish resource and the default 500 MWe max xlim meant the curve was very squished)

The team had some suggestions for the downloads as well, but this is all I have time for this weekend. 

I've gone ahead and merged this PR so the app is up to date, but give me a yell if you see anything that needs dealing with or have further ideas/suggestions.

### CODE REVIEW

**Review by rejexx — COMMENTED** [review]
Looking more professional and less hack-a-thon with these changes.  Nice work.  

For long text sections that are only markdown, you could consider moving to a separate markdown file which can be loaded and displayed with something like:
`st.markdown(get_file_content_as_string("intro.md"))`
Splitting the app into separate files might be more maintenance hassle than its worth, but it's one option.

**Comment by ICWallis** [comment]
That seems to be a good idea for the long text section, thanks @rejexx . I may have a look at this on the weekend when I go back in to fix all the typos in the markdown (I have a spell checker installed in my code editor, but it clearly isn't doing a good job". 

Bill wants to add a link that takes users to a list of caveats and general considerations (he is working on the text now). A colleague of mine suggested having a version with sliders for the input params so people can understand how their inputs changes the output. This would make another nice external link to a separate streamlit app.

**Comment by Japhiolite** [comment]
Back from holidays and just had a look. Totally agree: looks slick and way more professional now. Really great!
I personally appreciate the scaling-option for the x-axis. 

Haven't really any more ideas on the current one, but can help with the sliders if you want that get started :)

**Review by Japhiolite — COMMENTED** [review]
Back from holidays and just had a look. Totally agree: looks slick and way more professional now. Really great!
I personally appreciate the scaling-option for the x-axis, and the more detailed text (with step1, etc)

Haven't really any more ideas on the current one, but can help with the sliders if you want that get started :)

**Comment by ICWallis** [comment]
@Japhiolite It would be cool to work together on this. I opened it as an issue so we have somewhere to bounce some ideas inside. We could also get together for coffee to discuss sometime. Will Slack you. https://github.com/Geothermal-Resource-Capacity/Power-Density/issues/12#issue-997814606

**Pull request merged**
